# Generated by Django 2.1.1 on 2018-09-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_auto_20180920_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
