# Generated by Django 2.1.1 on 2018-09-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_auto_20180927_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pg6',
        ),
    ]
