# Generated by Django 2.1.1 on 2018-09-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_remove_profile_pg6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', unique=True),
        ),
    ]
