# Generated by Django 2.1.1 on 2018-09-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_auto_20180927_1931'),
        ('System', '0009_auto_20180927_1707'),
    ]

    operations = [
    ]
