# Generated by Django 2.1.1 on 2018-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_auto_20180928_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ugs',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
