# Generated by Django 2.1.1 on 2018-10-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0013_auto_20181005_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pg1',
            new_name='mca_sem1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pg2',
            new_name='mca_sem2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pg3',
            new_name='mca_sem3',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pg4',
            new_name='mca_sem4',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pg5',
            new_name='mca_sem5',
        ),
    ]
