# Generated by Django 2.1.1 on 2018-10-06 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0014_auto_20181005_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.CharField(max_length=40)),
                ('ipackage', models.CharField(max_length=40)),
                ('projectname', models.CharField(max_length=40)),
                ('seminar', models.CharField(max_length=40)),
                ('doji', models.DateField()),
                ('hrname', models.CharField(max_length=40)),
                ('hrcontact', models.CharField(max_length=40)),
                ('hremail', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
            options={
                'db_table': 'internship',
            },
        ),
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(max_length=40)),
                ('ppackage', models.CharField(max_length=40)),
                ('dojp', models.DateField()),
                ('hrname', models.CharField(max_length=40)),
                ('hrcontact', models.CharField(max_length=40)),
                ('hremail', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
            options={
                'db_table': 'placement',
            },
        ),
    ]
